### ISSUE TITLE
Discovery: Overrides for a subset of CCodes

### ISSUE THREAD

**Issue by blairlearn** [NCIOCPL/clinical-trials-listing-api#56]
# Review handling overrides for subsets of EVS' list of CCodes

In the process of resolving the missing trial overrides (issue #55), concerns were raised about the scenario where overrides had been used to split EVS value sets.

e.g. The EVS has a single concept for all forms of AML, which had previously been split into two groups of CCodes, one for Adult AML and one for Childhood AML.

The new system was created with explicit rules that if an override is missing some of the codes that EVS lists, then EVS is authoritative and the ingestion process uses the group from EVS.

This conflicts with the situation where you have groups which have been split as above.

### Tasks
- [ ]  Review the decision. Do we need to make changes in order to allow this scenario?
- [ ]  If so, what are the new processing rules?
- [ ] Once decisions are made, some form of the conflicting overrides (likely) need to be loaded into the system.

### Resources and Links
* Current processing rules: #2 
* [Old override files](https://github.com/NCIOCPL/wcms-front-end/tree/master/CancerGov/_src/FileAssets/Configuration/clinical-trials)
